default_install_hook_types: [pre-commit, prepare-commit-msg]
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        stages: [commit]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        stages: [commit]
        args: ["--profile", "black"]

  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
        stages: [commit]

  - repo: https://github.com/nonebot/nonemoji
    rev: v0.1.4
    hooks:
      - id: nonemoji
        stages: [prepare-commit-msg]
