name: trigger_remote_deploy

on:
  create:
    tags:
      - v*
    branchs:
      - "main"

jobs:
  send-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: call_webhook
        run: curl -X POST ${{ vars.REMOTE_CALL_URL }}
